### 스케줄 등록 테스트.
### profile 을 dev로 설정 후 테스트한다.
POST http://localhost:8080/api/schedules/tasks?userId=1
Content-Type: application/json

{
    "title" : "운동가기",
    "description" : "벤치프레스",
    "taskAt" : "2022-03-15T11:14:00"
}

### 이벤트 등록 테스트.
### profile 을 dev로 설정 후 테스트한다.
POST http://localhost:8080/api/schedules/events?userId=1
Content-Type: application/json

{
    "title" : "여행1",
    "description" : "강원도",
    "startAt" : "2022-03-16T16:00:00",
    "endAt" : "2022-03-17T16:00:00",
    "attendeeIds" : [2]
}

###
POST http://localhost:8080/save